### ISSUE TITLE
Minor Changes to Promo Code on Lowest Price Item

### ISSUE THREAD

**Issue by onedanshow** [Woodbolt-International/spree_wombat_adapter#12]
@apeacox Please see my suggestions on this commit: https://github.com/Woodbolt-International/spree_wombat_adapter/commit/f37fdb84bb5cd2ca7f69b323165e6ce74f6572d9

**Comment by apeacox** [comment]
Ok, fixed! Thank you for the suggestion, my fault I didn't thought about it earlier :P I'm going to update the gem on cellucor, royal and neon
